version: 2

deploy:
  steps:
    setupVariables:
      after:
        - name: Save private key to file
          run: |
            echo "$SSH_PRIVATE_KEY" > myKey.pem
            chmod 400 myKey.pem
