version: 1

deploy:
  steps:
    terraformInit:
      after:
      - terraform import aws_key_pair.key_pair ansible-control
  onSuccess:
    - echo "Deployment success - Add to hosts"

destroy:
  onSuccess:
    - echo "Destroy success - Remove from hosts"