# this file requires the following variables:
# $NAME: the name of the helm release
# $CHART: the name of the helm chart
# $FLAGS: options for running the template command e.g. `-set key=value`
version: 1

deploy:
  steps:
    setupVariables:
      after:
        - aws eks update-kubeconfig --name $CLUSTER_NAME --region us-west-2  
        - if [[ ! -e helm-v3.10.2-linux-amd64.tar.gz ]]; then; wget https://get.helm.sh/helm-v3.10.2-linux-amd64.tar.gz; fi;
        - tar -zxvf helm-v3.10.2-linux-amd64.tar.gz
        - ./linux-amd64/helm repo add bitnami https://charts.bitnami.com/bitnami 
        - ./linux-amd64/helm template $NAME $CHART $FLAGS > nginx.yaml
